version: "3.4"
services:
  'nifi':
    image: apache/nifi:latest
    ports:
     - "8080:8080"
  'elasticsearch':
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  'kibana':
    image: kibana:7.9.3
    ports: 
     - "5601:5601"
  '4305':
    image: py-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"

